FROM node:alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json /app

# Install dependencies
RUN npm install

# Update dependencies
RUN npm update

# Copy the rest of the application
COPY . /app

# Specify the port the app runs on
EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "dev"]